### ISSUE TITLE
Add binary releases

### ISSUE THREAD

**Issue by Arno0x** [moul/gotty-client#11]
Hi,

Is it possible to get binary releases for various platforms (my own interest goes to linux-armv7) like gotty does ?

Thanks,
Arno

**Comment by moul** [comment]
yep sure :)

I'm curious, what's the target ? RaspiV2 ? Scaleway ? Other ? :)

**Comment by moul** [comment]
I already built binaries for latest release, you can also find a linux-arm version: https://github.com/moul/gotty-client/releases/download/v1.0.1/gotty-client_1.0.1_linux_arm

It is built for armv5 for maximum compatibility but will works like a charm on armv7, I will create a new release tomorrow with latest features support

**Comment by Arno0x** [comment]
thanks ! The (current) target is Raspi 2 indeed.

**Comment by moul** [comment]
A new release is coming (binaries are uploading) https://github.com/moul/gotty-client/releases/v1.1.0
