### ISSUE TITLE
Bump goselect

### ISSUE THREAD

**Issue by moul** [moul/gotty-client#37]
goselect now have a better windows support (https://github.com/creack/goselect/pull/4)

**Comment by moul** [comment]
#38 just updated the goselect dependency

@QuentinPerez, what do you think about removing our windows hacks to let goselect do the job for us ?

**Comment by QuentinPerez** [comment]
Our windows hack is to discard the `SIGWINCH` signal ☺️

**Comment by moul** [comment]
Fixed with latest dependency bump
