### ISSUE TITLE
Authorization support [feature request]

### ISSUE THREAD

**Issue by nob-dy** [moul/gotty-client#50]
Since GoTTY server supports credentials settings and authorization i think it would be nice to have this in gotty-client too

**Comment by nob-dy** [comment]
Sorry didn't notice it's already implemented, i was just expecting to have appropriate command line option :)

For any other curious: creds should be in URI, e.g. http://user:password@host:port/

**Comment by moul** [comment]
Thanks :)
It worth a README update, do you want to open a pull request?
