### ISSUE TITLE
[documentation] Detaching from gotty session

### ISSUE THREAD

**Issue by msva** [moul/gotty-client#52]
Hi there!
As far as I can see, there is no any info anywhere even about the simple case: detach from remote gotty session (when you're done and want to leave). 😀 
It is neither documented in README, nor in gotty-client's help, not even on the internets (as far as I googled) 🤔

**Comment by moul** [comment]
Hi @msva,

Currently, the only solutions are:
* exiting the remote application (not possible for all the kind of applications)
* closing the window :)

It's possible to add a keyboard shortcut :) any idea about a good combination?

**Comment by msva** [comment]
> It's possible to add a keyboard shortcut :) any idea about a good
> combination?

Well, I guess, Ctrl+] (which is used, for example, by libvirt/lcx/openvz) 
would be fine, unless there is plans to add some another shortcuts/commands.

Otherwise — it would be nice to add some kind of «command mode», which will be 
activated by some combination (like Ctrl+A (in screen), Ctrl+B (in tmux), Ctrl
+^ (in mosh), and so on. Although, in that case, double pressing of such key 
combination should forward it «inside»).

Btw, `impiutil sol` uses `~` for that, and looks like it is fine with that 
(although, it also has the feature that double pressing «command mode» 
shortcut forwards it to the server).

**Comment by msva** [comment]
ping? :)

**Comment by moul** [comment]
Fixed in #54 :)
